### ISSUE TITLE
Fedora:29 'dnf update -y' fails on aarch64

### ISSUE THREAD

**Issue by nullterminated** [fedora-cloud/docker-brew-fedora#59]
Fedora:28 aarch64 works. Fedora:29 fails. Example docker file:

FROM fedora:29
RUN dnf update -y

Result:

Traceback (most recent call last):
  File "/usr/bin/dnf", line 58, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 179, in user_main
    errcode = main(args)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 64, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 99, in _main
    return cli_run(cli, base)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 123, in cli_run
    ret = resolving(cli, base)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 154, in resolving
    base.do_transaction(display=displays)
  File "/usr/lib/python3.7/site-packages/dnf/cli/cli.py", line 239, in do_transaction
    tid = super(BaseCli, self).do_transaction(display)
  File "/usr/lib/python3.7/site-packages/dnf/base.py", line 905, in do_transaction
    tid = self._run_transaction(cb=cb)
  File "/usr/lib/python3.7/site-packages/dnf/base.py", line 978, in _run_transaction
    tid = self.history.beg(rpmdbv, using_pkgs, [], cmdline)
  File "/usr/lib/python3.7/site-packages/dnf/db/history.py", line 448, in beg
    int(misc.getloginuid())
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by mattdm** [comment]
Can you file a bug against DNF for this, please? Thanks!

**Comment by nullterminated** [comment]
This seems to be resolved in Fedora 29 latest. dnf is v4.0.9 now.
